# fly.toml app configuration file generated for tsoha-firsbee on 2023-07-08T23:07:53+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tsoha-firsbee"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5000"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
